#Don't change | This is NOT the plugin version!
config_version: 1

debug: false

#OP-protection: Player can only be op'ed if they are in the "allowed-operators" list
op-protection: true
allowed-operators:
  - Admin
  - Console
#If you try to Op someone who isn't in the list
op-message: "&cThe Player isn't a listed operator!"
#Players who are operators and are not in the list can't connect and will be deop'ed.
unauthorized-operator-kick-message: '&cYou are not allowed to be an operator'

#Message if you type a blocked command | Enter none to disable
#Possible placeholders: {player}, {cmd}
blocked-command-message: "Unknown command. Type \"/help\" for help."
#Message shown if you type /pl | Enter none to disable | Players with the permission plhide.bypass will see the real plugins
/pl-message: 'Plugins (0):'

#Stay on the newest version to get better features!
#Enable or disable automatic ingame update notification on join
update-notify: false

#How many commands a player can send every 2 seconds
command_spam:
  amount: 40

groups:
  #if no group is set via plhide.group.<group> this will be applied to the player
  #do not rename the default group!
  #blocked commands will be automatically removed from the tabcompletion
  default:
    commands:
      - "!ver"
      - "!version"
      - "!about"
      - "!bukkit"
      - "!icanhasbukkit"
      - "!help"
      - "!?"
      - "!minecraft:help"
      - "!minecraft:me"
      - "!minecraft:msg"
      - "!minecraft:tell"
      - "!minecraft:w"
      - "!bukkit:?"
      - "!bukkit:help"
      - "!plugins"
      - "!pl"
      - "!bukkit:pl"
      - "!bukkit:plugins"
      - "!bukkit:ver"
      - "!bukkit:version"
      - "!bukkit:about"
      - "*"
      - "!br"
      - "!brush"
      - "!desel"
      - "!deselect"
      - "!toggleplace"
      - "!2fa"
      - "!advancedban"
      - "!advancedbanx:advancedban"
      - "!advancedbanx:ban"
      - "!advancedbanx:ban-ip"
      - "!advancedbanx:banip"
      - "!advancedbanx:banlist"
      - "!advancedbanx:change-reason"
      - "!advancedbanx:check"
      - "!advancedbanx:history"
      - "!advancedbanx:ipban"
      - "!advancedbanx:kick"
      - "!advancedbanx:mute"
      - "!advancedbanx:note"
      - "!advancedbanx:notes"
      - "!advancedbanx:systemprefs"
      - "!advancedbanx:tempban"
      - "!advancedbanx:tempipban"
      - "!advancedbanx:tempmute"
      - "!advancedbanx:tempwarn"
      - "!advancedbanx:tipban"
      - "!advancedbanx:unban"
      - "!advancedbanx:unmute"
      - "!advancedbanx:unnote"
      - "!advancedbanx:unpunish"
      - "!advancedbanx:unwarn"
      - "!advancedbanx:warn"
      - "!advancedbanx:warns"
      - "!ar"
      - "!authme"
      - "!authme:2fa"
      - "!authme:authme"
      - "!authme:captcha"
      - "!authme:email"
      - "!authme:totp"
      - "!authme:verification"
      - "!ban"
      - "!ban-ip"
      - "!banip"
      - "!banlist"
      - "!callowexplosions"
      - "!cautoclose"
      - "!cdefault"
      - "!cdisplay"
      - "!cdroptransfer"
      - "!change-reason"
      - "!;"
      - "!/br"
      - "!/brush"
      - "!/desel"
      - "!/deselect"
      - "!/sel"
      - "!/toggleplace"
      - "!autorestart"
      - "!chopper"
      - "!climits"
      - "!cmagnet"
      - "!cnolock"
      - "!cnospam"
      - "!crawl"
      - "!credstone"
      - "!csupply"
      - "!ctnt"
      - "!discordsrv"
      - "!discordsrv:discord"
      - "!discordsrv:discordsrv"
      - "!gcrawl"
      - "!glayback"
      - "!glay"
      - "!god"
      - "!gsit"
      - "!gsit:crawl"
      - "!gsit:gcrawl"
      - "!gsit:glay"
      - "!gsit:glayback"
      - "!gsit:gsit"
      - "!gsit:lay"
      - "!gsit:layback"
      - "!gsit:sit"
      - "!heal"
      - "!history"
      - "!invsee"
      - "!ipban"
      - "!kick"
      - "!layback"
      - "!authme:changepass"
      - "!authme:changepassword"
      - "!authme:cp"
      - "!authme:l"
      - "!authme:login"
      - "!authme:logout"
      - "!authme:reg"
      - "!authme:register"
      - "!authme:unregister"
      - "!check"
      - "!changepass"
      - "!authme:cp"
      - "!coreprotect:co"
      - "!cp"
      - "!email"
      - "!lp"
      - "!luckperms"
      - "!luckperms:lp"
      - "!luckperms:luckperms"
      - "!luckperms:perm"
      - "!luckperms:permission"
      - "!luckperms:permissions"
      - "!luckperms:perms"
      - "!lwc:callowexplosions"
      - "!lwc:cautoclose"
      - "!lwc:cdefault"
      - "!lwc:cdisplay"
      - "!lwc:cdonation"
      - "!lwc:cdroptransfer"
      - "!lwc:chopper"
      - "!lwc:cinfo"
      - "!lwc:climits"
      - "!lwc:cmagnet"
      - "!lwc:cmodify"
      - "!lwc:cnolock"
      - "!lwc:cnospam"
      - "!lwc:cpassword"
      - "!lwc:cpersist"
      - "!lwc:cprivate"
      - "!lwc:cpublic"
      - "!lwc:credstone"
      - "!lwc:cremove"
      - "!lwc:cremoveall"
      - "!lwc:csupply"
      - "!lwc:ctnt"
      - "!lwc:cunlock"
      - "!lwc:lock"
      - "!lwc:lwc"
      - "!lwc:unlock"
      - "!minecraft:teammsg"
      - "!minecraft:tm"
      - "!minecraft:trigger"
      - "!mute"
      - "!none"
      - "!note"
      - "!notes"
      - "!perm"
      - "!permission"
      - "!permissions"
      - "!perms"
      - "!plasmovoice:vlist"
      - "!plasmovoice:vrc"
      - "!playerhead"
      - "!playerhead:playerhead"
      - "!redstoneclockdetector:redstoneclockdetector"
      - "!redstoneclockdetector:rcd"
      - "!redstoneclockdetector"
      - "!region"
      - "!pl-hide-free:plhide"
      - "!plhide"
      - "!rg"
      - "!shopkeepers"
      - "!shopkeepers:shopkeepers"
      - "!shopkeepers:shopkeeper"
      - "!simpleclans:."
      - "!simpleclans:accept"
      - "!simpleclans:ally"
      - "!simpleclans:clan"
      - "!simpleclans:deny"
      - "!simpleclans:more"
      - "!skinsrestorer:skin"
      - "!slay"
      - "!systemprefs"
      - "!teammsg"
      - "!tempipban"
      - "!tipban"
      - "!tm"
      - "!tool"
      - "!totp"
      - "!tp2p"
      - ""
      - "!trigger"
      - "!uar"
      - "!ultimateautorestart:ultimateautorestart"
      - "!ultimateautorestart:uar"
      - "!ultimateautorestart:autorestart"
      - "!ultimateautorestart:ar"
      - "!unban"
      - "!ungod"
      - "!unnote"
      - "!unmute"
      - "!unpunish"
      - "!unreg"
      - "!unregister"
      - "!unwarn"
      - "!vset"
      - "!vanish"
      - "!verification"
      - "!vlist"
      - "!vrc"
      - "!warn"
      - "!warns"
      - "!we"
      - "!wesv"
      - "!worldedit"
      - "!worldedit:/br"
      - "!worldedit:/brush"
      - "!worldedit:/desel"
      - "!worldedit:/deselect"
      - "!worldedit:/sel"
      - "!worldedit:/toggleplace"
      - "!worldedit:;"
      - "!worldedit:br"
      - "!worldedit:brush"
      - "!worldedit:none"
      - "!worldedit:toggleplace"
      - "!worldedit:tool"
      - "!worldedit:we"
      - "!worldedit:worldedit"
      - "!worldeditselectionvisualizer"
      - "!worldeditselectionvisualizer:wesv"
      - "!worldeditselectionvisualizer:worldeditselectionvisualizer"
      - "!worldguard:god"
      - "!worldguard:heal"
      - "!worldguard:region"
      - "!worldguard:regions"
      - "!worldguard:rg"
      - "!worldguard:slay"
      - "!worldguard:ungod"
      - "!ultimateautorestart"
      - "!authme:unreg"
      - "!regions"
      - "!action"
      - "!ambient-debug"
      - "!cmdclientconfig"
      - "!config"
      - "!deathchest"
      - "!deathchest:deathchest"
      - "!describe"
      - "!eaction"
      - "!edelignore"
      - "!edescribe"
      - "!eignore"
      - "!ermignore"
      - "!ereply"
      - "!ermignore"
      - "!essentials:*"
      - "!etell"
      - "!eme"
      - "!emsg"
      - "!er"
      - "!epm"
      - "!eremignore"
      - "!essentials:action"
      - "!essentials:delignore"
      - "!essentials:describe"
      - "!essentials:eaction"
      - "!essentials:edelignore"
      - "!essentials:edescribe"
      - "!essentials:eignore"
      - "!essentials:eme"
      - "!essentials:emsg"
      - "!essentials:epm"
      - "!essentials:er"
      - "!essentials:eremignore"
      - "!essentials:ereply"
      - "!essentials:ermignore"
      - "!essentials:etell"
      - "!essentials:eunignore"
      - "!essentials:ewhisper"
      - "!essentials:ignore"
      - "!essentials:m"
      - "!essentials:me"
      - "!essentials:m"
      - "!essentials:msg"
      - "!essentials:pm"
      - "!essentials:r"
      - "!essentials:remignore"
      - "!essentials:reply"
      - "!essentials:rmignore"
      - "!essentials:t"
      - "!essentials:tell"
      - "!essentials:unignore"
      - "!essentials:w"
      - "!essentials:whisper"
      - "!eunignore"
      - "!ewhisper"
      - "!fcc"
      - "!ot"
      - "!plasmovoice:groups"
      - "!playtime:onlinetime"
      - "!playtime:ot"
      - "!playtime:playertime"
      - "!playtime:playtime"
      - "!playtime:pt"
      - "!playtime:timeplayed"
      - "!pt"
      - "!m"
      - "!remignore"
      - "!t"
      - "!voteban:addvote"
      - "!voteban:voteban"
      - "!voteban:votekick"
      - "!voteban:votemute"
      - "!rmignore"
      - "!alerts"
      - "!away"
      - "!config"
      - "!eafk"
      - "!eaway"
      - "!essentials:afk"
      - "!essentials:away"
      - "!essentials:eafk"
      - "!essentials:eaway"
      - "!jday"
      - "!logs"
      - "!punishlogs"
      - "!pv-addon-discs:disc"
      - "!tbconfig"
      - "!tbreload"
      - "!telegrambridge:tbconfig"
      - "!telegrambridge:tbm"
      - "!telegrambridge:tbmention"
      - "!telegrambridge:tbr"
      - "!telegrambridge:tbreload"
      - "!telegrambridge:tbreply"
      - "!voteban"
      - "!vulcan"
      - "!vulcan:alerts"
      - "!vulcan:jday"
      - "!vulcan:logs"
      - "!vulcan:punishlogs"
      - "!vulcan:vulcan"
      - "cunlock"
      - "floodgate"
      - "floodgate:floodgate"
      - "floodgate:linkaccount"
      - "floodgate:unlinkaccount"
      - "geyser"
      - "geyser-spigot:geyser"
      - "inventoryrollback"
      - "inventoryrollbackplus"
      - "inventoryrollbackplus:inventoryrollbackplus"
      - "inventoryrollbackplus:inventoryrollback"
      - "inventoryrollbackplus:ir"
      - "inventoryrollbackplus:irp"
      - "ir"
      - "irp"
      - "spigot:tps"
      - "afk"
    #If a player is in two groups, the group with the higher priority number is used
    #The minimum value is 0
    priority: 0
    #here you can add other groups
    #The group mode is taken from the main group, in this case the main group is "default"
    inherited-groups:
      - Test

  #This group for example will remove and block all commands
  #add permission plhide.group.test to apply this group
  Test:
    commands: []
    priority: 1
    inherited-groups: []
  #This group will allow all commands
  #add permission plhide.group.bypass to apply this group
  bypass:
    commands: 
      - "*"
    priority: 10
    inherited-groups: []
